/** snapshot-roles.ts 移植 — Playwright / Chrome 快照共用角色分类 */

export const INTERACTIVE_ROLES = new Set([
  'button',
  'checkbox',
  'combobox',
  'link',
  'listbox',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'radio',
  'searchbox',
  'slider',
  'spinbutton',
  'switch',
  'tab',
  'textbox',
  'treeitem',
]);

export const CONTENT_ROLES = new Set([
  'article',
  'cell',
  'columnheader',
  'gridcell',
  'heading',
  'listitem',
  'main',
  'navigation',
  'region',
  'rowheader',
]);

export const STRUCTURAL_ROLES = new Set([
  'application',
  'directory',
  'document',
  'generic',
  'grid',
  'group',
  'ignored',
  'list',
  'menu',
  'menubar',
  'none',
  'presentation',
  'row',
  'rowgroup',
  'table',
  'tablist',
  'toolbar',
  'tree',
  'treegrid',
]);
